# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comparator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63omparator.proto\"\'\n\x0bTopKRequest\x12\r\n\x05plans\x18\x01 \x03(\t\x12\t\n\x01k\x18\x02 \x01(\x03\"\x1e\n\x0cTopKResponse\x12\x0e\n\x06result\x18\x01 \x03(\x03\".\n\x0e\x43ompareRequest\x12\r\n\x05plans\x18\x01 \x03(\t\x12\r\n\x05pivot\x18\x02 \x01(\t\"3\n\x10\x42roadcastRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\t\x12\x11\n\tthreshold\x18\x02 \x03(\x03\"\x1e\n\x0c\x44\x61taResponse\x12\x0e\n\x06result\x18\x01 \x03(\x08\x32\xa9\x01\n\x11\x43omparatorService\x12-\n\x0cGetTopKPlans\x12\x0c.TopKRequest\x1a\r.TopKResponse\"\x00\x12/\n\x0b\x43ompareCost\x12\x0f.CompareRequest\x1a\r.DataResponse\"\x00\x12\x34\n\x0e\x43\x61nBeBroadcast\x12\x11.BroadcastRequest\x1a\r.DataResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'comparator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TOPKREQUEST']._serialized_start=20
  _globals['_TOPKREQUEST']._serialized_end=59
  _globals['_TOPKRESPONSE']._serialized_start=61
  _globals['_TOPKRESPONSE']._serialized_end=91
  _globals['_COMPAREREQUEST']._serialized_start=93
  _globals['_COMPAREREQUEST']._serialized_end=139
  _globals['_BROADCASTREQUEST']._serialized_start=141
  _globals['_BROADCASTREQUEST']._serialized_end=192
  _globals['_DATARESPONSE']._serialized_start=194
  _globals['_DATARESPONSE']._serialized_end=224
  _globals['_COMPARATORSERVICE']._serialized_start=227
  _globals['_COMPARATORSERVICE']._serialized_end=396
# @@protoc_insertion_point(module_scope)
